/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package object.project;

import javax.swing.JOptionPane;

/**
 *
 * @author green
 */
public class FurnitureGUI extends javax.swing.JFrame {

    
    String customerName , day , month, year, streetNum, streetName, city, state , zipCode;
    
    
    
    /**
     * Creates new form FurnitureGUI
     */
    public FurnitureGUI() {
        initComponents();
        CustomerFrame.setVisible(false);
        ItemFrame.setVisible(false);
        OrderFrame.setVisible(false);
        
        
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerFrame = new javax.swing.JFrame();
        HomeCustomer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CustomerName = new javax.swing.JFormattedTextField();
        StreetNumber = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        StreetName = new javax.swing.JFormattedTextField();
        City = new javax.swing.JFormattedTextField();
        State = new javax.swing.JFormattedTextField();
        ZipCode = new javax.swing.JFormattedTextField();
        CreateCustomer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustomerInfoBox = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        Day = new javax.swing.JFormattedTextField();
        Month = new javax.swing.JFormattedTextField();
        Year = new javax.swing.JFormattedTextField();
        ItemFrame = new javax.swing.JFrame();
        HomeItem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ChairItemButton = new javax.swing.JRadioButton();
        DiningTableItemButton = new javax.swing.JRadioButton();
        SofaItemButton = new javax.swing.JRadioButton();
        StorageCabinateItemButton = new javax.swing.JRadioButton();
        BedItemButton = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Dimention1 = new javax.swing.JTextField();
        Dimention2 = new javax.swing.JTextField();
        Dimention3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        MaterialType = new javax.swing.JTextField();
        Color = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        ChairsList = new javax.swing.JTextField();
        NumberOfDrawers = new javax.swing.JTextField();
        CreateItem = new javax.swing.JButton();
        OrderFrame = new javax.swing.JFrame();
        HomeOrder = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CustomerNameOrder = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        DayOrder = new javax.swing.JFormattedTextField();
        MonthOrder = new javax.swing.JFormattedTextField();
        YearOrder = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TotalPrice = new javax.swing.JFormattedTextField();
        CreateOrder = new javax.swing.JButton();
        ChairOrder = new javax.swing.JCheckBox();
        SofaOrder = new javax.swing.JCheckBox();
        StorageCabinateOrder = new javax.swing.JCheckBox();
        DiningTableOrder = new javax.swing.JCheckBox();
        BedOrder = new javax.swing.JCheckBox();
        SearchGroup = new javax.swing.ButtonGroup();
        ItemGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        AddCustomer = new javax.swing.JButton();
        AddItem = new javax.swing.JButton();
        AddOrder = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CustomerSearch = new javax.swing.JRadioButton();
        OrderSearch = new javax.swing.JRadioButton();
        ItemSearch = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchResults = new javax.swing.JTextArea();
        EnterInfo = new javax.swing.JFormattedTextField();
        DisplayOrders = new javax.swing.JButton();

        CustomerFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        CustomerFrame.setPreferredSize(new java.awt.Dimension(521, 364));
        CustomerFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                CustomerFrameWindowOpened(evt);
            }
        });

        HomeCustomer.setText("Return Home");
        HomeCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeCustomerMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Add a New Customer");

        CustomerName.setText("Customer Name");

        StreetNumber.setText("Street Number");

        jLabel7.setText("Enter Customer Name");

        jLabel8.setText("Enter Address:");

        StreetName.setText("Street Name");

        City.setText("City");

        State.setText("State");

        ZipCode.setText("Zip Code");

        CreateCustomer.setText("Create Customer");
        CreateCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateCustomerMouseClicked(evt);
            }
        });

        CustomerInfoBox.setEditable(false);
        CustomerInfoBox.setColumns(20);
        CustomerInfoBox.setRows(5);
        jScrollPane2.setViewportView(CustomerInfoBox);

        jLabel9.setText("Date Of Birth");

        Day.setText("Day");

        Month.setText("Month");

        Year.setText("Year");

        javax.swing.GroupLayout CustomerFrameLayout = new javax.swing.GroupLayout(CustomerFrame.getContentPane());
        CustomerFrame.getContentPane().setLayout(CustomerFrameLayout);
        CustomerFrameLayout.setHorizontalGroup(
            CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerFrameLayout.createSequentialGroup()
                .addGroup(CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CustomerFrameLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomerFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CustomerFrameLayout.createSequentialGroup()
                                        .addGroup(CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CustomerFrameLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateCustomer)
                            .addComponent(StreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomeCustomer)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        CustomerFrameLayout.setVerticalGroup(
            CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CustomerFrameLayout.createSequentialGroup()
                        .addComponent(StreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(CustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeCustomer)
                    .addComponent(CreateCustomer))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        ItemFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        ItemFrame.setPreferredSize(new java.awt.Dimension(521, 364));
        ItemFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                ItemFrameWindowOpened(evt);
            }
        });

        HomeItem.setText("Return Home");
        HomeItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeItemMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Add a New Item");

        jLabel10.setText("Select Item Type");

        ChairItemButton.setText("Chair");
        ChairItemButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChairItemButtonItemStateChanged(evt);
            }
        });

        DiningTableItemButton.setText("Dining Table");
        DiningTableItemButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DiningTableItemButtonItemStateChanged(evt);
            }
        });

        SofaItemButton.setText("Sofa");
        SofaItemButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SofaItemButtonItemStateChanged(evt);
            }
        });

        StorageCabinateItemButton.setText("Storage Cabinate");
        StorageCabinateItemButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StorageCabinateItemButtonItemStateChanged(evt);
            }
        });

        BedItemButton.setText("Bed");
        BedItemButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BedItemButtonItemStateChanged(evt);
            }
        });

        jLabel11.setText("Add Specifications");

        jLabel12.setText("Dimentions:");

        jLabel13.setText("X");

        jLabel14.setText("X");

        jLabel15.setText("Material Type:");

        jLabel16.setText("Color:");

        jLabel17.setText("Price:");

        jLabel18.setText("List of Chairs:");

        jLabel19.setText("Number of Drawers:");

        CreateItem.setText("Add Item");
        CreateItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateItemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ItemFrameLayout = new javax.swing.GroupLayout(ItemFrame.getContentPane());
        ItemFrame.getContentPane().setLayout(ItemFrameLayout);
        ItemFrameLayout.setHorizontalGroup(
            ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemFrameLayout.createSequentialGroup()
                .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ItemFrameLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(ItemFrameLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ChairItemButton)
                                            .addComponent(DiningTableItemButton)
                                            .addComponent(SofaItemButton)
                                            .addComponent(StorageCabinateItemButton)
                                            .addComponent(BedItemButton))))
                                .addGap(30, 30, 30)
                                .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(ItemFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dimention1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dimention2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dimention3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ItemFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MaterialType, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ItemFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ItemFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ItemFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ChairsList, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ItemFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NumberOfDrawers, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(ItemFrameLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(CreateItem))
                    .addGroup(ItemFrameLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(HomeItem)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        ItemFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Dimention1, Dimention2, Dimention3});

        ItemFrameLayout.setVerticalGroup(
            ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChairItemButton)
                    .addComponent(jLabel12)
                    .addComponent(Dimention1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dimention2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dimention3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SofaItemButton)
                    .addComponent(jLabel15)
                    .addComponent(MaterialType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiningTableItemButton)
                    .addComponent(jLabel16)
                    .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BedItemButton)
                    .addComponent(jLabel17)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StorageCabinateItemButton)
                    .addComponent(jLabel18)
                    .addComponent(ChairsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ItemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(NumberOfDrawers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CreateItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(HomeItem)
                .addGap(15, 15, 15))
        );

        OrderFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        OrderFrame.setPreferredSize(new java.awt.Dimension(521, 364));
        OrderFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                OrderFrameWindowOpened(evt);
            }
        });

        HomeOrder.setText("Return Home");
        HomeOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeOrderMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Create a New Order");

        CustomerNameOrder.setText("Customer Name");
        CustomerNameOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameOrderActionPerformed(evt);
            }
        });

        jLabel20.setText("Enter Information");

        DayOrder.setText("Day");

        MonthOrder.setText("Month");

        YearOrder.setText("Year");

        jLabel21.setText("Date Of Order");

        jLabel22.setText("Ordered Items");

        TotalPrice.setText("TotalPrice");
        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        CreateOrder.setText("Create Order");
        CreateOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateOrderMouseClicked(evt);
            }
        });

        ChairOrder.setText("Chair");

        SofaOrder.setText("Sofa");

        StorageCabinateOrder.setText("Storage Cabinate");

        DiningTableOrder.setText("Dining Table");

        BedOrder.setText("Bed");

        javax.swing.GroupLayout OrderFrameLayout = new javax.swing.GroupLayout(OrderFrame.getContentPane());
        OrderFrame.getContentPane().setLayout(OrderFrameLayout);
        OrderFrameLayout.setHorizontalGroup(
            OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderFrameLayout.createSequentialGroup()
                .addGroup(OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OrderFrameLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel20)))
                .addGap(106, 106, 106))
            .addGroup(OrderFrameLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderFrameLayout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(DayOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MonthOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(YearOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(OrderFrameLayout.createSequentialGroup()
                        .addGroup(OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderFrameLayout.createSequentialGroup()
                                .addGroup(OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SofaOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChairOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BedOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DiningTableOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(StorageCabinateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerNameOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addGroup(OrderFrameLayout.createSequentialGroup()
                                .addGroup(OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CreateOrder)
                                    .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92)
                                .addComponent(HomeOrder)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        OrderFrameLayout.setVerticalGroup(
            OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(12, 12, 12)
                .addComponent(CustomerNameOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(DayOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChairOrder)
                    .addComponent(DiningTableOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SofaOrder)
                    .addComponent(BedOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StorageCabinateOrder)
                .addGroup(OrderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomeOrder)
                        .addGap(17, 17, 17))
                    .addGroup(OrderFrameLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CreateOrder)
                        .addContainerGap(23, Short.MAX_VALUE))))
        );

        SearchGroup.add(CustomerSearch);
        SearchGroup.add(ItemSearch);
        SearchGroup.add(OrderSearch);

        ItemGroup.add(ChairItemButton);
        ItemGroup.add(SofaItemButton);
        ItemGroup.add(DiningTableItemButton);
        ItemGroup.add(BedItemButton);
        ItemGroup.add(StorageCabinateItemButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Furniture Ordering System");

        AddCustomer.setLabel("Add New Customer");
        AddCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCustomerMouseClicked(evt);
            }
        });

        AddItem.setLabel("Add New Item");
        AddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddItemMouseClicked(evt);
            }
        });

        AddOrder.setLabel("Create Order");
        AddOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddOrderMouseClicked(evt);
            }
        });

        Search.setText("Search ");
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Search");

        CustomerSearch.setText("Customer");
        CustomerSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CustomerSearchItemStateChanged(evt);
            }
        });

        OrderSearch.setText("Order");
        OrderSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OrderSearchItemStateChanged(evt);
            }
        });

        ItemSearch.setText("Item");
        ItemSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ItemSearchItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Add New Elements");

        SearchResults.setEditable(false);
        SearchResults.setColumns(20);
        SearchResults.setRows(5);
        jScrollPane1.setViewportView(SearchResults);

        EnterInfo.setText("Enter Information");

        DisplayOrders.setText("Display Orders");
        DisplayOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayOrdersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ItemSearch)
                        .addComponent(OrderSearch)
                        .addComponent(CustomerSearch)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EnterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddCustomer)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(DisplayOrders)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCustomer)
                    .addComponent(AddItem)
                    .addComponent(AddOrder))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OrderSearch)
                        .addGap(19, 19, 19)
                        .addComponent(EnterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search)
                    .addComponent(DisplayOrders))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCustomerMouseClicked
        // TODO add your handling code here:
        //System.out.print("Click");
        CustomerFrame.setVisible(true);
        //CustomerPanel.setVisible(true);
        
    }//GEN-LAST:event_AddCustomerMouseClicked

    private void HomeCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeCustomerMouseClicked
        // TODO add your handling code here:
        CustomerFrame.setVisible(false);
    }//GEN-LAST:event_HomeCustomerMouseClicked

    private void CustomerFrameWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_CustomerFrameWindowOpened
        
        CustomerFrame.setSize(500,500);
    }//GEN-LAST:event_CustomerFrameWindowOpened

    private void AddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddItemMouseClicked
        
        ItemFrame.setVisible(true);
    }//GEN-LAST:event_AddItemMouseClicked

    private void HomeItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeItemMouseClicked
        
        ItemFrame.setVisible(false);
    }//GEN-LAST:event_HomeItemMouseClicked

    private void ItemFrameWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ItemFrameWindowOpened
        ItemFrame.setSize(500,500);
    }//GEN-LAST:event_ItemFrameWindowOpened

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        // TODO add your handling code here:
        if (CustomerSearch.isSelected() ) {
            
        }
        
        if (ItemSearch.isSelected() ) {
            System.out.print("item");
            //EnterInfo.setText("Enter Item Name");
        }
        
        if (OrderSearch.isSelected() ) {
            System.out.print("order");
            //EnterInfo.setText("Enter Customer Name");
        }
        
        SearchResults.setText("Search Results for: " + EnterInfo.getText() + "\n");
        
    }//GEN-LAST:event_SearchMouseClicked

    private void AddOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddOrderMouseClicked
        OrderFrame.setVisible(true);
    }//GEN-LAST:event_AddOrderMouseClicked

    private void CustomerSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CustomerSearchItemStateChanged
        // TODO add your handling code here:
         if (CustomerSearch.isSelected() ) {
           
            EnterInfo.setText("Enter Customer Name");
        }
        
        if (ItemSearch.isSelected() ) {
            
            EnterInfo.setText("Enter Item Name");
        }
        
        if (OrderSearch.isSelected() ) {
            
            EnterInfo.setText("Enter Customer Name");
        }
    }//GEN-LAST:event_CustomerSearchItemStateChanged

    private void ItemSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ItemSearchItemStateChanged
        // TODO add your handling code here:
         if (CustomerSearch.isSelected() ) {
           
            EnterInfo.setText("Enter Customer Name");
        }
        
        if (ItemSearch.isSelected() ) {
            
            EnterInfo.setText("Enter Item Name");
        }
        
        if (OrderSearch.isSelected() ) {
            
            EnterInfo.setText("Enter Customer Name");
        }
    }//GEN-LAST:event_ItemSearchItemStateChanged

    private void OrderSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OrderSearchItemStateChanged
        // TODO add your handling code here:
         if (CustomerSearch.isSelected() ) {
           
            EnterInfo.setText("Enter Customer Name");
        }
        
        if (ItemSearch.isSelected() ) {
            
            EnterInfo.setText("Enter Item Name");
        }
        
        if (OrderSearch.isSelected() ) {
            
            EnterInfo.setText("Enter Customer Name");
        }
    }//GEN-LAST:event_OrderSearchItemStateChanged

    private void CreateCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateCustomerMouseClicked
        
        
        //verify that text is entered into all spots
        
        if (CustomerName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a Customer Name");
            CustomerInfoBox.setText("");
        } else {
            customerName = CustomerName.getText();
        }
        
        if (Day.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a Day");
            CustomerInfoBox.setText("");
        } else {
            day = Day.getText();
        }
        
        if (Month.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a Month");
            CustomerInfoBox.setText("");
        } else {
            month = Month.getText();
        }
        
        if (Year.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a Year");
            CustomerInfoBox.setText("");
        }else {
            year = Year.getText();
        }
        
        if (StreetNumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a street number");
            CustomerInfoBox.setText("");
        } else {
            streetNum = StreetNumber.getText();
        }
        
        if (StreetName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a street name");
            CustomerInfoBox.setText("");
        }else {
            streetName = StreetName.getText();
        }
        
        if (City.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a city");
            CustomerInfoBox.setText("");
        } else {
            city = City.getText();
        }
        
        if (State.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a state");
            CustomerInfoBox.setText("");
        } else {
            state = State.getText();
        }
        
        if (ZipCode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a zip code");
            CustomerInfoBox.setText("");
        }else {
            zipCode = ZipCode.getText();
        }
        
        // numbers only for date, street num, zip code
        boolean flag = true;

        for (int i = 0; i < streetNum.length(); i++) {
            if (!Character.isDigit(streetNum.charAt(i))) {
                flag = false;
                break;
            }
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(null, "The street number must have only digits");
            CustomerInfoBox.setText("");
        } else {
            streetNum=StreetNumber.getText();
        }

        flag = true;
        
        for (int i = 0; i < zipCode.length(); i++) {
            if (!Character.isDigit(zipCode.charAt(i))) {
                flag = false;
                break;
            }
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(null, "The zip code must have only digits");
            CustomerInfoBox.setText("");
        } else {
            zipCode = ZipCode.getText();
        }

        flag = true;
        
        for (int i = 0; i < day.length(); i++) {
            if (!Character.isDigit(day.charAt(i))) {
                flag = false;
                break;
            }
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(null, "The day must have only digits");
            CustomerInfoBox.setText("");
        } else {
            day = Day.getText();
        }

        flag = true;
        
        for (int i = 0; i < month.length(); i++) {
            if (!Character.isDigit(month.charAt(i))) {
                flag = false;
                break;
            }
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(null, "The month must have only digits");
            CustomerInfoBox.setText("");
        } else {
            month = Month.getText();
        }

        flag = true;
        
        for (int i = 0; i < year.length(); i++) {
            if (!Character.isDigit(year.charAt(i))) {
                flag = false;
                break;
            }
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(null, "The year must have only digits");
            CustomerInfoBox.setText("");
        } else {
            year=Year.getText();
        }

        flag = true;
        
        int dayInt = Integer.parseInt(Day.getText());
        int monthInt = Integer.parseInt(Month.getText());
        int yearInt = Integer.parseInt(Year.getText());
        int streetNumInt = Integer.parseInt(StreetNumber.getText());
        int zipCodeInt = Integer.parseInt(ZipCode.getText());
        
        CustomerInfoBox.setText(CustomerName.getText() + "\n" + StreetNumber.getText() + " " + StreetName.getText() + "\n" + City.getText() + " , " + State.getText() + " " + ZipCode.getText() );
        
        Customer customer = new Customer(customerName, dayInt, monthInt, yearInt, streetNumInt, streetName, city, state, zipCodeInt);
        
        //have this part actually create a customer with the displayed information
        
        
    }//GEN-LAST:event_CreateCustomerMouseClicked

    private void ChairItemButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChairItemButtonItemStateChanged
        if (ChairItemButton.isSelected() ) {
            ChairsList.setEditable(false);
            ChairsList.setText("N/A");
            NumberOfDrawers.setEditable(false);
            NumberOfDrawers.setText("N/A");
        }
    }//GEN-LAST:event_ChairItemButtonItemStateChanged

    private void SofaItemButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SofaItemButtonItemStateChanged
        if (SofaItemButton.isSelected() ) {
            ChairsList.setEditable(false);
            ChairsList.setText("N/A");
             NumberOfDrawers.setEditable(false);
             NumberOfDrawers.setText("N/A");
        }
    }//GEN-LAST:event_SofaItemButtonItemStateChanged

    private void DiningTableItemButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DiningTableItemButtonItemStateChanged
        if(DiningTableItemButton.isSelected()) {
            ChairsList.setEditable(true);
            ChairsList.setText("");
            NumberOfDrawers.setEditable(false);
            NumberOfDrawers.setText("N/A");
        }
    }//GEN-LAST:event_DiningTableItemButtonItemStateChanged

    private void BedItemButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BedItemButtonItemStateChanged
        if (BedItemButton.isSelected() ) {
            ChairsList.setEditable(false);
            ChairsList.setText("N/A");
            NumberOfDrawers.setEditable(false);
            NumberOfDrawers.setText("N/A");
        }
    }//GEN-LAST:event_BedItemButtonItemStateChanged

    private void StorageCabinateItemButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StorageCabinateItemButtonItemStateChanged
        if (StorageCabinateItemButton.isSelected() ) {
            ChairsList.setEditable(false);
            ChairsList.setText("N/A");
            NumberOfDrawers.setEditable(true);
            NumberOfDrawers.setText("");
            
            

        }
    }//GEN-LAST:event_StorageCabinateItemButtonItemStateChanged

    private void CreateItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateItemMouseClicked
        // TODO add your handling code here:
        
        if (Dimention1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a dimention");
        }
        
        if (Dimention2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a dimention");
        }
        
        if (Dimention3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a dimention");
        }
        
        if (MaterialType.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a material type");
        }
        
        if (Color.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a color");
        }
        
        if (Price.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a price");
        }
        
        
        if (NumberOfDrawers.getText().isEmpty() && StorageCabinateItemButton.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please Enter a number of drawers");
        }
        
         if (ChairsList.getText().isEmpty() && DiningTableItemButton.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please Enter a number of drawers");
        }
         
         JOptionPane.showMessageDialog(null, "Item Added");

        
    }//GEN-LAST:event_CreateItemMouseClicked

    private void OrderFrameWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_OrderFrameWindowOpened
        // TODO add your handling code here:
        OrderFrame.setSize(500,500);
    }//GEN-LAST:event_OrderFrameWindowOpened

    private void CreateOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateOrderMouseClicked
        // TODO add your handling code here:

        if (CustomerNameOrder.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a Customer Name");

        }

        if (DayOrder.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a Day");

        }

        if (MonthOrder.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a Month");

        }

        if (YearOrder.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a Year");

        }

        if (TotalPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter a price");
        }

        String yearOrder=YearOrder.getText(), monthOrder=MonthOrder.getText(), dayOrder=DayOrder.getText() ;

        boolean flag = true;

        for (int i = 0; i < dayOrder.length(); i++) {
            if (!Character.isDigit(dayOrder.charAt(i))) {
                flag = false;
                break;
            }
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(null, "The day must have only digits");
            CustomerInfoBox.setText("");
        } else {
            dayOrder = DayOrder.getText();
        }

        flag = true;

        for (int i = 0; i < monthOrder.length(); i++) {
            if (!Character.isDigit(monthOrder.charAt(i))) {
                flag = false;
                break;
            }
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(null, "The month must have only digits");
            CustomerInfoBox.setText("");
        } else {
            monthOrder = MonthOrder.getText();
        }

        flag = true;

        for (int i = 0; i < yearOrder.length(); i++) {
            if (!Character.isDigit(yearOrder.charAt(i))) {
                flag = false;
                break;
            }
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(null, "The year must have only digits");
            CustomerInfoBox.setText("");
        } else {
            yearOrder = YearOrder.getText();
        }

        flag = true;
        
        JOptionPane.showMessageDialog(null, "Order Created");
    }//GEN-LAST:event_CreateOrderMouseClicked

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void CustomerNameOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameOrderActionPerformed

    private void HomeOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeOrderMouseClicked
        // TODO add your handling code here:
        OrderFrame.setVisible(false);
    }//GEN-LAST:event_HomeOrderMouseClicked

    private void DisplayOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayOrdersMouseClicked
        // TODO add your handling code here:
        SearchResults.setText("Orders: ");
    }//GEN-LAST:event_DisplayOrdersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FurnitureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FurnitureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FurnitureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FurnitureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FurnitureGUI().setVisible(true);
            }
        });
        
        //Date.Date(day,month,year);
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomer;
    private javax.swing.JButton AddItem;
    private javax.swing.JButton AddOrder;
    private javax.swing.JRadioButton BedItemButton;
    private javax.swing.JCheckBox BedOrder;
    private javax.swing.JRadioButton ChairItemButton;
    private javax.swing.JCheckBox ChairOrder;
    private javax.swing.JTextField ChairsList;
    private javax.swing.JFormattedTextField City;
    private javax.swing.JTextField Color;
    private javax.swing.JButton CreateCustomer;
    private javax.swing.JButton CreateItem;
    private javax.swing.JButton CreateOrder;
    private javax.swing.JFrame CustomerFrame;
    private javax.swing.JTextArea CustomerInfoBox;
    private javax.swing.JFormattedTextField CustomerName;
    private javax.swing.JFormattedTextField CustomerNameOrder;
    private javax.swing.JRadioButton CustomerSearch;
    private javax.swing.JFormattedTextField Day;
    private javax.swing.JFormattedTextField DayOrder;
    private javax.swing.JTextField Dimention1;
    private javax.swing.JTextField Dimention2;
    private javax.swing.JTextField Dimention3;
    private javax.swing.JRadioButton DiningTableItemButton;
    private javax.swing.JCheckBox DiningTableOrder;
    private javax.swing.JButton DisplayOrders;
    private javax.swing.JFormattedTextField EnterInfo;
    private javax.swing.JButton HomeCustomer;
    private javax.swing.JButton HomeItem;
    private javax.swing.JButton HomeOrder;
    private javax.swing.JFrame ItemFrame;
    private javax.swing.ButtonGroup ItemGroup;
    private javax.swing.JRadioButton ItemSearch;
    private javax.swing.JTextField MaterialType;
    private javax.swing.JFormattedTextField Month;
    private javax.swing.JFormattedTextField MonthOrder;
    private javax.swing.JTextField NumberOfDrawers;
    private javax.swing.JFrame OrderFrame;
    private javax.swing.JRadioButton OrderSearch;
    private javax.swing.JTextField Price;
    private javax.swing.JButton Search;
    private javax.swing.ButtonGroup SearchGroup;
    private javax.swing.JTextArea SearchResults;
    private javax.swing.JRadioButton SofaItemButton;
    private javax.swing.JCheckBox SofaOrder;
    private javax.swing.JFormattedTextField State;
    private javax.swing.JRadioButton StorageCabinateItemButton;
    private javax.swing.JCheckBox StorageCabinateOrder;
    private javax.swing.JFormattedTextField StreetName;
    private javax.swing.JFormattedTextField StreetNumber;
    private javax.swing.JFormattedTextField TotalPrice;
    private javax.swing.JFormattedTextField Year;
    private javax.swing.JFormattedTextField YearOrder;
    private javax.swing.JFormattedTextField ZipCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
